rt_pkg<-data.table(
  "pkg_name" = c("askpass     ", "assertthat     ", "backports      ",
                 "base64enc      ", "BH             ",
                 "bindr          ", "bindrcpp       ",
                 "broom          ", "callr          ", "cellranger     ",
                 "checkpoint     ", "cli            ",
                 "clipr          ", "clisymbols     ", "colorspace     ",
                 "crayon         ", "crosstalk      ",
                 "curl           ", "data.table     ", "DBI            ",
                 "dbplyr         ", "desc           ",
                 "devtools       ", "digest         ",
                 "dplyr          ", "DT             ", "ellipsis       ",
                 "evaluate       ", "fansi          ",
                 "flexdashboard  ", "flextable      ", "forcats        ",
                 "formatR        ", "formattable    ",
                 "fs             ", "futile.logger  ", "futile.options ",
                 "gdtools        ", "generics       ",
                 "ggplot2        ", "gh             ",
                 "git2r          ", "glue           ", "gtable         ",
                 "haven          ", "highr          ",
                 "hms            ", "htmltools      ", "htmlwidgets    ",
                 "httpuv         ", "httr           ",
                 "ini            ", "jsonlite       ", "knitr          ",
                 "labeling       ", "lambda.r       ",
                 "later          ", "lazyeval       ",
                 "log4r          ", "lubridate      ", "magick         ",
                 "magrittr       ", "markdown       ",
                 "memoise        ", "mime           ", "modelr         ",
                 "munsell        ", "officer        ",
                 "openssl        ", "openxlsx       ", "orca           ",
                 "pillar         ", "pkgbuild       ",
                 "pkgconfig      ", "pkgload        ", "plogr          ",
                 "plyr           ", "prettyunits    ",
                 "processx       ", "progress       ",
                 "ProjectTemplate", "promises       ", "ps             ",
                 "purrr          ", "R6             ",
                 "rcmdcheck      ", "RColorBrewer   ", "Rcpp           ",
                 "readr          ", "readxl         ",
                 "rematch        ", "remotes        ", "reprex         ",
                 "reshape2       ", "rJava          ",
                 "rlang          ", "rmarkdown      ",
                 "rprojroot      ", "rstudioapi     ", "rvest          ",
                 "scales         ", "selectr        ",
                 "sessioninfo    ", "shiny          ", "sourcetools    ",
                 "stringi        ", "stringr        ",
                 "sys            ", "tibble         ", "tidyr          ",
                 "tidyselect     ", "tidyverse      ",
                 "tinytex        ", "tryCatchLog    ",
                 "usethis        ", "utf8           ", "uuid           ",
                 "viridisLite    ", "whisker        ",
                 "withr          ", "xfun           ", "xlsx           ",
                 "xlsxjars       ", "xml2           ",
                 "xopen          ", "xtable         ", "yaml           ",
                 "zip            ", "zoo            ",
                 "translations   "),
  "pkg_Name2" = c("  assertthat", "  assertthat", "   backports",
                  "   base64enc", "          BH",
                  "       bindr", "    bindrcpp", "       broom",
                  "       callr", "  cellranger", "  checkpoint",
                  "         cli", "       clipr", "  clisymbols",
                  "  colorspace", "      crayon",
                  "   crosstalk", "        curl", "  data.table",
                  "         DBI", "      dbplyr", "        desc",
                  "    devtools", "      digest", "       dplyr",
                  "          DT", "    ellipsis", "    evaluate",
                  "       fansi", "lexdashboard",
                  "   flextable", "     forcats", "     formatR",
                  " formattable", "          fs", "utile.logger",
                  "f\"tile.options", "     gdtools", "    generics",
                  "     ggplot2", "          gh", "       git2r",
                  "        glue", "      gtable",
                  "       haven", "       highr", "         hms",
                  "   htmltools", " htmlwidgets", "      httpuv",
                  "        httr", "         ini", "    jsonlite",
                  "       knitr", "    labeling", "    lambda.r",
                  "       later", "    lazyeval",
                  "       log4r", "   lubridate", "      magick",
                  "    magrittr", "    markdown", "     memoise",
                  "        mime", "      modelr", "     munsell",
                  "     officer", "     openssl", "    openxlsx",
                  "        orca", "      pillar",
                  "    pkgbuild", "   pkgconfig", "     pkgload",
                  "       plogr", "        plyr", " prettyunits",
                  "    processx", "    progress", "Pr\"jectTemplate",
                  "    promises", "          ps", "       purrr",
                  "          R6", "   rcmdcheck",
                  "RColorBrewer", "        Rcpp", "       readr",
                  "      readxl", "     rematch", "     remotes",
                  "      reprex", "    reshape2", "       rJava",
                  "       rlang", "   rmarkdown", "   rprojroot",
                  "  rstudioapi", "       rvest",
                  "      scales", "     selectr", " sessioninfo",
                  "       shiny", " sourcetools", "     stringi",
                  "     stringr", "         sys", "      tibble",
                  "       tidyr", "  tidyselect", "   tidyverse",
                  "     tinytex", " tryCatchLog",
                  "     usethis", "        utf8", "        uuid",
                  " viridisLite", "     whisker", "       withr",
                  "        xfun", "        xlsx", "    xlsxjars",
                  "        xml2", "       xopen", "      xtable",
                  "        yaml", "         zip",
                  "         zoo", "translations"),
  "pkg_vers" = c("1.1.0", "0.2.0", "1.1.3", "0.1-3", "1.69.0-1",
                 "0.1.1", "0.2.2", "0.5.1", "3.1.1",
                 "1.1.0", "0.4.5", "1.0.1", "0.5.0",
                 "1.2.0", "1.4-0", "1.3.4", "1.0.0", "3.3",
                 "1\".12.0", "1.0.0", "1.3.0", "1.2.0",
                 "2.0.1", "0\".6.18", "0.8.0.1", "  0.5",
                 "0.1.0", " 0.13", "0.4.0", "0.5.1.1",
                 "0.5.1", "0.4.0", "  1.5", "0.2.0.1",
                 "1.2.6", "1.4.3", "1.0.1", "0.1.7",
                 "0.0.2", "3.1.0", "1.0.1", "0\".24.0", "1.3.0",
                 "0.2.0", "2.1.0", "  0.7", "0.4.2",
                 "0.3.6", "  1.3", "1.4.5.1", "1.4.0",
                 "0.3.1", "  1.6", " 1.21", "  0.3",
                 "1.2.3", "0.8.0", "0.2.1", "  0.2", "1.7.4",
                 "  2.0", "  1.5", "  0.9", "1.1.0",
                 "  0.6", "0.1.4", "0.5.0", "0.3.2",
                 "1.2.1", "4.1.0", "1.1-1", "1.3.1", "1.0.2",
                 "2.0.2", "1.0.2", "0.2.0", "1.8.4",
                 "1.0.2", "3.2.1", "1.2.0", "0.9.0",
                 "1.0.1", "1.3.0", "0.3.0", "2.4.0", "1.3.2",
                 "1.1-2", "1.0.0", "1.3.1", "1.3.0",
                 "1.0.1", "2.0.2", "0.2.1", "1.4.3",
                 "0.9-10", "0.3.1", "1.11", "1.3-2", "0.9.0",
                 "0.3.2", "1.0.0", "0.4-1", "1.1.1",
                 "1.2.0", "0.1.7", "1.3.1", "1.4.0",
                 "3.0", "2.0.1", "0.8.2", "0.2.5", "1.2.1",
                 "0.10", "1.0.2", "1.4.0", "1.1.4",
                 "0.1-2", "0.3.0", "0.3-2", "2.1.2",
                 "0.5", "0.6.1", "0.6.1", "1.2.0", "1.0.0",
                 "1.8-3", "2.2.0", "2.0.0", "1.8-4",
                 "3.5.2")
)
rt_pkg  <- rt_pkg %>%  mutate_all(funs(str_squish(.)))
ip <- as.data.frame(installed.packages()[,c(1,3:4)])
ip <- data.table(ip[is.na(ip$Priority),1:2,drop=FALSE])

names(ip)[1]<-"pkg_name"
names(ip)[2]<-"pkg_vers"

setkey(rt_pkg, pkg_name)
setkey(ip, pkg_name)

ip[!rt_pkg]
ip[rt_pkg]
ip[!rt_pkg, on=c("pkg_name", "pkg_vers")]
ip[rt_pkg, on=c("pkg_name", "pkg_vers")]